# Generated by Django 3.0.5 on 2020-05-02 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_childcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='child_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_comments', to='community.Comment'),
        ),
        migrations.DeleteModel(
            name='ChildComment',
        ),
    ]
