# Generated by Django 3.0.5 on 2020-05-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20200502_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='child_comment',
            new_name='parent_comment',
        ),
    ]
